# Generated by Django 5.2 on 2025-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdetailinfo',
            name='contentid',
            field=models.PositiveIntegerField(),
        ),
    ]
