# Generated by Django 5.2 on 2025-06-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdetailcommon',
            name='summarize',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarize', to='items.contentsummarize'),
        ),
    ]
