# Generated by Django 5.2 on 2025-06-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_contentdetailcommon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdetailcommon',
            name='summarize',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarize', to='items.contentsummarize', to_field='contentid'),
        ),
    ]
