# Generated by Django 5.2 on 2025-06-03 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_cards/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='interactions.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('click', '클릭'), ('bookmark', '찜'), ('like', '좋아요'), ('dislike', '싫어요'), ('share', '공유'), ('duration', '체류시간')], max_length=20)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_interaction',
                'indexes': [models.Index(fields=['user', 'content_id', 'action_type'], name='content_int_user_id_e30d17_idx'), models.Index(fields=['action_type', 'timestamp'], name='content_int_action__1aa087_idx'), models.Index(fields=['content_id'], name='content_int_content_9a02aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.questionnaire')),
                ('selected_cards', models.ManyToManyField(to='interactions.questioncard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'questionnaire')},
            },
        ),
    ]
