# Generated by Django 5.2 on 2025-06-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('items', '0003_alter_contentdetailcommon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentinteraction',
            name='content',
            field=models.ForeignKey(db_column='content_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='items.contentdetailcommon', to_field='contentid'),
        ),
    ]
