# Generated by Django 5.2 on 2025-06-07 11:18

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', pgvector.django.vector.VectorField(dimensions=484)),
                ('food', pgvector.django.vector.VectorField(dimensions=484)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '전역 선호도 프로필',
                'db_table': 'global_preference_profile',
            },
        ),
        migrations.CreateModel(
            name='CategoryHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.categoryhierarchy')),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bookmark',
                'unique_together': {('user', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', pgvector.django.vector.VectorField(blank=True, dimensions=484, null=True)),
                ('food', pgvector.django.vector.VectorField(blank=True, dimensions=484, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preference_profile',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['experience'], m=16, name='experience_hnsw_idx', opclasses=['vector_cosine_ops']), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['food'], m=16, name='food_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['user'], name='user_prefer_user_id_b317c3_idx')],
            },
        ),
    ]
