# Generated by Django 5.2 on 2025-06-10 03:51

from django.db import migrations

def create_initial_global_profile(apps, schema_editor):
    GlobalPreferenceProfile = apps.get_model('users', 'GlobalPreferenceProfile')
    if not GlobalPreferenceProfile.objects.exists():
        GlobalPreferenceProfile.objects.create(
            experience=[0.0]*484,
            food=[0.0]*484
        )

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),  # 이전 마이그레이션 지정
    ]

    operations = [
        migrations.RunPython(create_initial_global_profile),
    ]
