# Generated by Django 5.2 on 2025-06-11 10:08

import apps.users.models
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250610_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferenceprofile',
            name='experience',
            field=pgvector.django.vector.VectorField(blank=True, default=apps.users.models.default_vector, dimensions=484),
        ),
        migrations.AlterField(
            model_name='userpreferenceprofile',
            name='food',
            field=pgvector.django.vector.VectorField(blank=True, default=apps.users.models.default_vector, dimensions=484),
        ),
    ]
