# Generated by Django 5.2 on 2025-06-07 11:18

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFeature',
            fields=[
                ('detail', models.OneToOneField(db_column='contentid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature', serialize=False, to='items.contentdetailcommon')),
                ('feature_vector', pgvector.django.vector.VectorField(blank=True, dimensions=484, null=True)),
            ],
            options={
                'db_table': 'content_feature',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['feature_vector'], m=16, name='feature_vector_cosine_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
