# Generated by Django 5.2 on 2025-06-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_contentdetailcommon_summarize'),
        ('recommender', '0002_remove_contentfeature_feature_vector_cosine_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfeature',
            name='detail',
            field=models.OneToOneField(db_column='detail_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature', serialize=False, to='items.contentdetailcommon'),
        ),
    ]
